name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/gcloud-go .

      - name: Unit tests
        run: go test ./...
